### ISSUE TITLE
Add support for Thumbor-supported fit-in modes 

### ISSUE THREAD

**Issue by Antoniossss** [square/pollexor#30]
Thumbor supports 3 modes to fit-in according to the doc
```
https://github.com/thumbor/thumbor/wiki/Usage
```

These modes are:
* Fit-in
* Full-fit-in
* Adaptive-fit-int

Please add url builder support for that.

**Comment by JakeWharton** [comment]
Released in 2.0.4 which will be available in Maven central in about 10 minutes.
